# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: da55aacfe4eede76da4bb7751b9138f2fb91a7cccdaa1d8e04af505f62e072c479d1ee427fc8d4e6b920bb747033ac9e2b42c92d39901dc84b45e8d9dd0629b7

test:
  secret_key_base: e97c1f750af61c4c4fdd889d4d030222ed8c02a360ca3bb17fb24f8533eb08ff189eee3383359e32c2bde4dcb40c5bb712078e06ccbf8b12b2609f0d7eb79168

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
